name: Build package

on: [push, pull_request]

jobs:
  sentry-cli:
    name: Build sentry-cli
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: sentry-cli
      - name: Run cargo build
        run: |
          cd sentry-cli
          cargo build --release --locked
      - uses: actions/upload-artifact@v4
        with:
          name: sentry-cli
          path: sentry-cli/target/release/sentry-cli.exe

  native-sdk:
    name: Build SDK
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./sentry-native
    strategy:
      matrix:
        platform: [Win32, x64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Configure CMake
      run: cmake -B build -A ${{ matrix.platform }} -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSENTRY_BUILD_EXAMPLES=OFF -DSENTRY_BUILD_TESTS=OFF
    - name: Build
      run: cmake --build build --parallel --config RelWithDebInfo
    - name: Install
      run: cmake --install build --prefix install --config RelWithDebInfo
    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: sentry-native-${{ matrix.platform }}
        path: sentry-native/install/

  build-nuget:
    name: Build NuGet package
    runs-on: windows-latest
    needs: [sentry-cli, native-sdk]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fetch SDK binaries (Win32)
        uses: actions/download-artifact@v4
        with:
          name: sentry-native-Win32
          path: Win32
      - name: Fetch SDK binaries (x64)
        uses: actions/download-artifact@v4
        with:
          name: sentry-native-x64
          path: x64
      - name: Fetch sentry-cli
        uses: actions/download-artifact@v4
        with:
          name: sentry-cli
      - name: List available files
        run: gci . -Recurse -File
      - name: Build NuGet package
        run: nuget pack Unofficial.Sentry.Native.nuspec -Verbosity detailed
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: "*.nupkg"

  publish-nuget:
    name: Publish NuGet
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: build-nuget
    steps:
      - name: Fetch artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package

      - uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-api-key-source: https://www.nuget.org/api/v2/package

      - name: Publish to NuGet
        run: nuget push *.nupkg -Source https://www.nuget.org/api/v2/package
